feat: loader component and store.
DD-DeCaF/caffeine pull request #53
Opened 2018-09-12 12:12 UTC by AlbaLopez

2018-09-12 12:34 UTC, matyasfodor requested changes

2018-09-12 12:34 UTC, matyasfodor commented on src/app/loader/store/loader.actions.ts
> +  readonly type = LOADING;
Do we use this?

2018-09-12 12:34 UTC, matyasfodor commented on src/app/loader/store/loader.actions.ts
> +  readonly type = LOADING_SUCCESS;
And this one?

2018-09-12 12:34 UTC, matyasfodor commented on src/app/loader/store/loader.reducers.ts
> +        loading: state.count === 0,
Add a selector for this please (or since you only read this value once, it's ok to do it in the component)

2018-09-13 12:49 UTC, matyasfodor commented on src/app/app-interactive-map/app-interactive-map.component.ts
> +          console.log('LOADIIIING', loading);
please remove

2018-09-13 13:04 UTC, matyasfodor requested changes

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/app-interactive-map.component.ts
> +          const dialogConfig = new MatDialogConfig();
can you create this config outside the subscribe? Only the logic that needs to be here should be here (it's faster too!)

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/app-interactive-map.component.ts
> +          setTimeout(() => this.dialog.open(LoaderComponent, dialogConfig), 0);
why do you need a timeout?

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/components/loader/loader.component.ts
> +
too many blank lines

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/components/loader/loader.component.ts
> +
no need for blank line here

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/components/loader/store/loader.reducers.ts
> +        count: ++state.count,
please use `state.count + 1`

In this case it doesn't matter, but `++` changes the value of the original object which is bad practice.

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/components/loader/store/loader.reducers.ts
> +        count: --state.count,
same here

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/components/loader/store/loader.reducers.ts
> +      default:
indentation is off

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/store/interactive-map.effects.ts
> +    map(() => {
Please just use `mapTo`, it's more simple https://www.learnrxjs.io/operators/transformation/mapto.html

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/store/interactive-map.effects.ts
> +  incrementRequest: Observable<Action> = combineLatest(
why don't you just
```
incrementRequest: Observable<Action> = this.actions$.pipe(
  ofType(fromActions.FETCH_SPECIES, fromActions.FETCH_MODELS, fromActions.FETCH_MAPS),
  mapTo(new loaderActions.Increment()),
);
```
Please add loader for operations also

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app.component.scss
> +
I guess you didn't want to commit this

2018-09-13 13:04 UTC, matyasfodor commented on src/app/app-interactive-map/app-interactive-map.component.scss
> +
Please clean up this. Leave only one blank line at the end of the file

2018-09-13 13:34 UTC, AlbaLopez commented on src/app/app-interactive-map/app-interactive-map.component.ts
> +          setTimeout(() => this.dialog.open(LoaderComponent, dialogConfig), 0);
I dont why if you try to open a dialog inside of the subscribe you have an error, it is the only way to skip the error.

2018-09-13 14:11 UTC, matyasfodor commented on src/app/app-interactive-map/app-interactive-map.component.ts
> +          setTimeout(() => this.dialog.open(LoaderComponent, dialogConfig), 0);
What's the error?

2018-09-13 14:16 UTC, matyasfodor commented on src/app/app-interactive-map/app-interactive-map.component.ts
> +          const dialogConfig = new MatDialogConfig();
You can still move out this bit from subscribe

2018-09-13 14:17 UTC, AlbaLopez commented on src/app/app-interactive-map/app-interactive-map.component.ts
> +          setTimeout(() => this.dialog.open(LoaderComponent, dialogConfig), 0);
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'id: undefined'. Current value: 'id: mat-dialog-0'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

2018-09-13 15:03 UTC, matyasfodor commented on src/app/app-interactive-map/app-interactive-map.component.ts
> +          setTimeout(() => this.dialog.open(LoaderComponent, dialogConfig), 0);
I wanted you to add the comment inside the `if`, just before the `setTimeout` :D https://github.com/DD-DeCaF/caffeine/pull/53/files#diff-fbbc852574ed9718241743f70b6af746R102

2018-09-13 15:46 UTC, matyasfodor approved these changes

2018-09-14 14:07 UTC, merged